apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: quizapp
  name: quizapp-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quizapp-be
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quizapp-be
    spec:
      serviceAccountName: dgpub-secrets-manager-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: quizapp-be-spc
      containers:
      - name: quizapp-be
        imagePullPolicy: IfNotPresent
        ports:
          - name: tcp
            containerPort: 3000
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true
        env:
          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                name: quizapp-be-secret
                key: NODE_ENV
          